S04 feature viewdatas
WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Form pull request #39
Opened 2023-11-19 18:58 UTC by Phalenopsis

2023-11-19 20:40 UTC, msmithfc300 approved these changes
excited to combine our two pages for the collated results!

2023-11-19 20:57 UTC, yoyodes1000 approved these changes

2023-11-20 08:44 UTC, WilliamTahar requested changes

2023-11-20 08:44 UTC, WilliamTahar commented on src/Model/CSVManager.php
> +        $data = [$formId]; // line just for grumphp, the method will be implement later or erase
Pourquoi n'affectes-tu pas directement avec **$formId** ?

2023-11-20 08:44 UTC, WilliamTahar commented on src/Model/CSVManager.php
> +        $data = [$formId]; // line just for grumphp, the method will be implement later or erase
De plus en l'état la variable ne sert à rien, tu peux directement retourner la valeur

2023-11-20 08:44 UTC, WilliamTahar commented on src/Model/CompletedFormManager.php
> +        $returns = $statement->fetchAll();
Tu peux return directement

2023-11-20 08:44 UTC, WilliamTahar commented on src/Model/CompletedFormManager.php
> +        $returns = $statement->fetchAll();
Tu peux return directement

2023-11-20 08:44 UTC, WilliamTahar commented on src/Model/DataViewManager.php
> +        $data = $this->prepareCharts($data);
idem

2023-11-20 08:44 UTC, WilliamTahar commented on src/Model/DataViewManager.php
> +        foreach ($datas as $key => $data) {
Voir **array_map**

2023-11-20 08:44 UTC, WilliamTahar commented on src/Model/DataViewManager.php
> +        foreach ($map as $x => $y) {
array_map

2023-11-20 08:44 UTC, WilliamTahar commented on src/Model/SavedFormManager.php
> +        $returns = $statement->fetchAll();
return directement

2023-11-20 09:00 UTC, Phalenopsis commented on src/Model/CSVManager.php
> +        $data = [$formId]; // line just for grumphp, the method will be implement later or erase
méthode effacée, elle ne sert à rien au final

2023-11-20 09:02 UTC, Phalenopsis commented on src/Model/CompletedFormManager.php
> +        $returns = $statement->fetchAll();
fait

2023-11-20 09:04 UTC, Phalenopsis commented on src/Model/DataViewManager.php
> +        $data = $this->prepareCharts($data);
fait (mais c'était pratique de ne pas return directement pour le var_dump)

2023-11-20 10:29 UTC, merged